Traceback (most recent call last):
  File "/opt/jupyterhub/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/jupyterhub/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/jupyterhub/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# first read and render to get imgae sizing 
img_array = imageio.imread("/home/sensei/ce-5319-webroot/1-Databases/MaterialCracking/UT-881/Image0.png", as_gray = True)
img_data = 255.0 - img_array.reshape(16384)
#img_data = ((img_data/255.0)*0.99) + 0.01
matplotlib.pyplot.imshow(numpy.asfarray(img_data).reshape((128,128)),cmap = 'Greys') # construct a graphic object #
matplotlib.pyplot.show() # show the graphic object to a window #
matplotlib.pyplot.close('all')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;66;03m# first read and render to get imgae sizing [39;00m
[0;32m----> 2[0m img_array [38;5;241m=[39m [43mimageio[49m[38;5;241;43m.[39;49m[43mimread[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m/home/sensei/ce-5319-webroot/1-Databases/MaterialCracking/UT-881/Image0.png[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mas_gray[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[1;32m      3[0m img_data [38;5;241m=[39m [38;5;241m255.0[39m [38;5;241m-[39m img_array[38;5;241m.[39mreshape([38;5;241m16384[39m)
[1;32m      4[0m [38;5;66;03m#img_data = ((img_data/255.0)*0.99) + 0.01[39;00m

File [0;32m/opt/jupyterhub/lib/python3.10/site-packages/imageio/v2.py:359[0m, in [0;36mimread[0;34m(uri, format, **kwargs)[0m
[1;32m    356[0m imopen_args [38;5;241m=[39m decypher_format_arg([38;5;28mformat[39m)
[1;32m    357[0m imopen_args[[38;5;124m"[39m[38;5;124mlegacy_mode[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m--> 359[0m [38;5;28;01mwith[39;00m [43mimopen[49m[43m([49m[43muri[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mri[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mimopen_args[49m[43m)[49m [38;5;28;01mas[39;00m file:
[1;32m    360[0m     result [38;5;241m=[39m file[38;5;241m.[39mread(index[38;5;241m=[39m[38;5;241m0[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    362[0m [38;5;28;01mreturn[39;00m result

File [0;32m/opt/jupyterhub/lib/python3.10/site-packages/imageio/core/imopen.py:113[0m, in [0;36mimopen[0;34m(uri, io_mode, plugin, extension, format_hint, legacy_mode, **kwargs)[0m
[1;32m    111[0m     request[38;5;241m.[39mformat_hint [38;5;241m=[39m format_hint
[1;32m    112[0m [38;5;28;01melse[39;00m:
[0;32m--> 113[0m     request [38;5;241m=[39m [43mRequest[49m[43m([49m[43muri[49m[43m,[49m[43m [49m[43mio_mode[49m[43m,[49m[43m [49m[43mformat_hint[49m[38;5;241;43m=[39;49m[43mformat_hint[49m[43m,[49m[43m [49m[43mextension[49m[38;5;241;43m=[39;49m[43mextension[49m[43m)[49m
[1;32m    115[0m source [38;5;241m=[39m [38;5;124m"[39m[38;5;124m<bytes>[39m[38;5;124m"[39m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(uri, [38;5;28mbytes[39m) [38;5;28;01melse[39;00m uri
[1;32m    117[0m [38;5;66;03m# fast-path based on plugin[39;00m
[1;32m    118[0m [38;5;66;03m# (except in legacy mode)[39;00m

File [0;32m/opt/jupyterhub/lib/python3.10/site-packages/imageio/core/request.py:249[0m, in [0;36mRequest.__init__[0;34m(self, uri, mode, extension, format_hint, **kwargs)[0m
[1;32m    246[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mInvalid Request.Mode: [39m[38;5;132;01m{[39;00mmode[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    248[0m [38;5;66;03m# Parse what was given[39;00m
[0;32m--> 249[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_parse_uri[49m[43m([49m[43muri[49m[43m)[49m
[1;32m    251[0m [38;5;66;03m# Set extension[39;00m
[1;32m    252[0m [38;5;28;01mif[39;00m extension [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/opt/jupyterhub/lib/python3.10/site-packages/imageio/core/request.py:409[0m, in [0;36mRequest._parse_uri[0;34m(self, uri)[0m
[1;32m    406[0m [38;5;28;01mif[39;00m is_read_request:
[1;32m    407[0m     [38;5;66;03m# Reading: check that the file exists (but is allowed a dir)[39;00m
[1;32m    408[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m os[38;5;241m.[39mpath[38;5;241m.[39mexists(fn):
[0;32m--> 409[0m         [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m([38;5;124m"[39m[38;5;124mNo such file: [39m[38;5;124m'[39m[38;5;132;01m%s[39;00m[38;5;124m'[39m[38;5;124m"[39m [38;5;241m%[39m fn)
[1;32m    410[0m [38;5;28;01melse[39;00m:
[1;32m    411[0m     [38;5;66;03m# Writing: check that the directory to write to does exist[39;00m
[1;32m    412[0m     dn [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mdirname(fn)

[0;31mFileNotFoundError[0m: No such file: '/home/sensei/ce-5319-webroot/1-Databases/MaterialCracking/UT-881/Image0.png'

